# Generated by Django 4.1.4 on 2023-06-12 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.TextField(blank=True, help_text='Дополнительная информация о пользователе', null=True, verbose_name='О себе'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='achievements',
            field=models.TextField(blank=True, null=True, verbose_name='Академические достижения'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='favorite_subjects',
            field=models.TextField(blank=True, null=True, verbose_name='Любимые школьные предметы'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
