# Generated by Django 4.2.5 on 2023-11-12 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_historicalcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created_at'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
