# Generated by Django 4.2.5 on 2023-11-12 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_news_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalnews',
            name='short_text',
            field=models.TextField(editable=False, null=True, verbose_name='Укороченнный текст'),
        ),
        migrations.AddField(
            model_name='news',
            name='short_text',
            field=models.TextField(editable=False, null=True, verbose_name='Укороченнный текст'),
        ),
    ]
