# Generated by Django 4.1.4 on 2023-01-07 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0002_university_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='logo_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на логотип'),
        ),
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(help_text='Например: 09.03.01', max_length=512, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=512, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='department',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='universities.university', verbose_name='Университет'),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specializations', to='universities.department', verbose_name='Направление'),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='name',
            field=models.CharField(max_length=512, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='university',
            name='city',
            field=models.CharField(default='Москва', max_length=512, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='university',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.CharField(max_length=512, verbose_name='Название'),
        ),
    ]
