# Generated by Django 4.1.4 on 2023-05-12 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_alter_subject_name'),
        ('universities', '0003_university_logo_url_alter_department_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialization',
            name='subjects',
            field=models.ManyToManyField(related_name='specializations', to='subjects.subject', verbose_name='Набор предметов'),
        ),
    ]
