# Generated by Django 4.1.4 on 2023-05-15 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0004_specialization_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='short_description',
            field=models.TextField(blank=True, null=True, verbose_name='Краткое описание'),
        ),
    ]
